# fly.toml app configuration file generated for givery-recip-ancient-voice-46 on 2025-09-14T21:25:20+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'givery-recip-ancient-voice-46'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'recipes_data'
  destination = '/app/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
